### ISSUE TITLE
Unable to install on OSX (Macbook Pro)

### ISSUE THREAD

**Issue by mkummer225** [microsoft/node-speech#48]
I'm getting the following error when trying to install this package into my extension project; `npm i @vscode/node-speech`:
```
npm ERR! command failed
npm ERR! command sh -c pwsh setup-packages.ps1 && node preinstall.js
npm ERR! sh: pwsh: command not found
```

npm@10.2.4
node@v20.11.0

<details> 

```
npm verb cli /Users/.../.nvm/versions/node/v20.11.0/bin/node /Users/.../.nvm/versions/node/v20.11.0/bin/npm
npm info using npm@10.2.4
npm info using node@v20.11.0
npm verb title npm i @vscode/node-speech
npm verb argv "i" "--loglevel" "verbose" "@vscode/node-speech"
npm verb logfile logs-max:10 dir:/Users/.../.npm/_logs/2024-10-08T18_04_35_101Z-
npm verb logfile /Users/.../.npm/_logs/2024-10-08T18_04_35_101Z-debug-0.log
npm verb shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
npm http fetch GET 200 https://registry.npmjs.org/@vscode%2fnode-speech 801ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/node-addon-api 62ms (cache revalidated)
npm http fetch GET 200 https://registry.npmjs.org/yauzl 124ms (cache revalidated)
npm verb reify failed optional dependency .../node_modules/@lancedb/vectordb-win32-x64-msvc
npm verb reify failed optional dependency .../node_modules/@lancedb/vectordb-linux-x64-gnu
npm verb reify failed optional dependency .../node_modules/@lancedb/vectordb-linux-arm64-gnu
npm verb reify failed optional dependency .../node_modules/@lancedb/vectordb-darwin-arm64
npm info run @vscode/node-speech@1.4.0 install node_modules/@vscode/node-speech pwsh setup-packages.ps1 && node preinstall.js
npm info run @vscode/node-speech@1.4.0 install { code: 127, signal: null }
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (/Users/.../.nvm/versions/node/v20.11.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
npm verb stack     at ChildProcess.emit (node:events:518:28)
npm verb stack     at maybeClose (node:internal/child_process:1105:16)
npm verb stack     at Socket.<anonymous> (node:internal/child_process:457:11)
npm verb stack     at Socket.emit (node:events:518:28)
npm verb stack     at Pipe.<anonymous> (node:net:337:12)
npm verb pkgid @vscode/node-speech@1.4.0
npm verb cwd ...
npm verb Darwin 20.6.0
npm verb node v20.11.0
npm verb npm  v10.2.4
npm ERR! code 127
npm ERR! path .../node_modules/@vscode/node-speech
npm ERR! command failed
npm ERR! command sh -c pwsh setup-packages.ps1 && node preinstall.js
npm ERR! sh: pwsh: command not found
npm verb exit 127
npm verb unfinished npm timer reify 1728410675552
npm verb unfinished npm timer reify:audit 1728410677295
npm verb unfinished npm timer auditReport:getReport 1728410677295
npm verb unfinished npm timer reify:build 1728410677364
npm verb unfinished npm timer build 1728410677365
npm verb unfinished npm timer build:deps 1728410677365
npm verb unfinished npm timer build:run:install 1728410677366
npm verb unfinished npm timer build:run:install:node_modules/@vscode/node-speech 1728410677367
npm verb code 127
```
</details>

**Comment by bpasero** [comment]
See https://learn.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.4

**Comment by mkummer225** [comment]
I now get 
```
npm ERR! make: *** No rule to make target `../.cache/SpeechSDK/runtimes/osx-x64/native/libMicrosoft.CognitiveServices.Speech.core.dylib', needed by `Release/libMicrosoft.CognitiveServices.Speech.core.dylib'.  Stop.
```

In addition to installing pwsh via your link, I also followed the instructions on [this page](https://learn.microsoft.com/en-us/azure/ai-services/speech-service/quickstarts/setup-platform?tabs=macos%2Cubuntu%2Cpowershell%2Cdotnet%2Cjre%2Cmaven%2Cnodejs%2Cmac%2Cpypi&pivots=programming-language-cpp) to install the `Microsoft.CognitiveServices.Speech` package[1] but it seems it still needs to be built(?)

<details>

```
npm ERR! path /.../node_modules/@vscode/node-speech
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@20.11.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.12.6 found at "/usr/local/opt/python@3.12/bin/python3.12"
npm ERR! gyp info spawn /usr/local/opt/python@3.12/bin/python3.12
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/.../node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/.../node_modules/@vscode/node-speech/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/.../node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/.../Library/Caches/node-gyp/20.11.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/.../Library/Caches/node-gyp/20.11.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/.../node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/.../Library/Caches/node-gyp/20.11.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/.../node_modules/@vscode/node-speech',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! make: *** No rule to make target `../.cache/SpeechSDK/runtimes/osx-x64/native/libMicrosoft.CognitiveServices.Speech.core.dylib', needed by `Release/libMicrosoft.CognitiveServices.Speech.core.dylib'.  Stop.
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/.../node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/Users/.../.nvm/versions/node/v20.11.0/bin/node" "/.../node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /.../node_modules/@vscode/node-speech
npm ERR! gyp ERR! node -v v20.11.0
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok
```
</details>

[1]`pwsh -Command "Install-Package Microsoft.CognitiveServices.Speech"`
